name:                decision-diagrams
version:             0.3.0.0
github:              "msakai/haskell-decision-diagrams"
license:             BSD3
author:              "Masahiro Sakai"
maintainer:          "masahiro.sakai@gmail.com"
copyright:           "2021 Masahiro Sakai"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Binary Decision Diagrams (BDD) and Zero-suppressed Binary Decision Diagrams (ZDD)
category:            Data, Data Structures, Logic, Formal Methods

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/msakai/haskell-decision-diagrams#readme>

dependencies:
- base >=4.11.0.0 && <5
- containers >=0.5.11.0 && <0.8
- mwc-random >=0.13.6.0 && <0.16
- graphviz

other-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- RankNTypes
- ScopedTypeVariables

library:
  source-dirs: src
  other-modules:
  - Data.DecisionDiagram.BDD.Internal.Node
  dependencies:
  - hashable >=1.2.7.0 && <1.6
  - hashtables >=1.2.3.1 && <1.4
  - intern >=0.9.1.2 && <1.0.0.0
  - primitive >=0.6.3.0 && <0.10
  - random >=1.1 && <1.3
  - reflection >=2.1.4 && <2.2
  - unordered-containers >=0.2.9.0 && <0.3
  - vector >=0.12.0.2 && <0.14
  other-extensions:
  - CPP
  - DeriveGeneric
  - DeriveTraversable
  - GeneralizedNewtypeDeriving
  - PatternSynonyms
  - TypeFamilies
  - UndecidableInstances
  - ViewPatterns

tests:
  decision-diagrams-test:
    main:                TestSuite.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decision-diagrams
    - deepseq >=1.4.3.0 && <1.6
    - QuickCheck >=2.11.3 && <2.16
    - quickcheck-instances >=0.3.19 && <0.4
    - statistics >=0.14.0.2 && <0.17
    - tasty >=1.1.0.4 && <1.6
    - tasty-hunit >=0.10.0.1 && <0.11
    - tasty-quickcheck >=0.10 && <0.12
    - tasty-th >=0.1.7 && <0.2
    - vector >=0.12.0.2 && <0.14
    other-extensions:
    - TemplateHaskell
  decision-diagrams-doctest:
    main: test/doctests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decision-diagrams
    - doctest
